### ISSUE TITLE
Which diff tool is producing that "patch file"?

### ISSUE THREAD

**Issue by ChristianWeissCG** [krishicks/yaml-patch#11]
Usually patch tools are used in combination with diff tools.
What diff tool for yaml files is producing such a "RFC6902-ish YAML document"?

```---
- op: add
  path: /baz/waldo
  value: fred
```

**Comment by ChristianWeissCG** [comment]
You maybe want to discuss / collaborate here: https://github.com/sahilm/yamldiff/issues/7

**Comment by krishicks** [comment]
Hi! The patch files are meant to be made by hand, not by a diff tool.
