### ISSUE TITLE
Add Operation with Sub-Element Match

### ISSUE THREAD

**Issue by nickwallen** [krishicks/yaml-patch#19]
I am attempting to add a field after performing a sub-element match.  Should I expect this to work?  I am not sure if I am just abusing your fine library or if I should expect this to work.  Or maybe there is an alternative way to do this?

The input document.
```
➜ cat input.yaml 
---
jobs:
- name: alpha
- name: beta
```
With this patch I want to add a new field `history` to the job named `alpha`.
```
➜ cat patch.yaml 
---
- op: add
  path: /jobs/name=alpha/history
  value: [ pending ]
```
When applying the patch to this input, I get an error.
```
➜ cat input.yaml | yaml-patch -o patch.yaml 
2020/06/09 12:12:38 error applying patch: could not expand pointer: /jobs/name=alpha/history
```
I was expecting the output to look like this.
```
---
jobs:
- name: alpha
   history:
  - started
- name: beta
```

**Comment by krishicks** [comment]
Hi,

In this case you would need to use `replace` and also provide the key=value that you used to find the array item:

```yaml
---
- op: replace
  path: /jobs/name=alpha
  value:
    name: alpha
    history:
      - started
```

```sh
> cat input.yaml | yaml-patch -o patch.yaml
jobs:
- history:
  - started
  name: alpha
- name: beta
```
