### ISSUE TITLE
Support path including '/'

### ISSUE THREAD

**Issue by datianshi** [krishicks/yaml-patch#2]
https://github.com/krishicks/yaml-patch/blob/573fa0ebecb1a2388b3441a2f933e9c5d2ec2824/pathfinder.go#L26

The path matcher is using '/' as delimiter to find. This would break the value itself contains '/'
Needs to support a way to quote '/' as search string

**Comment by krishicks** [comment]
`yaml-patch` now supports escape ordering when using the extended `/key=value` syntax: https://tools.ietf.org/html/rfc6902#appendix-A.14

`name: A/B` can be targeted via `/name=A~1B`
