### ISSUE TITLE
element in an array within an array is not being removed correctly

### ISSUE THREAD

**Issue by mevansam** [krishicks/yaml-patch#3]
When I try to remove an element of an array within an array using a search path, yaml-patch is deleting the element before the actual element to be deleted.

YAML to be patched: https://raw.githubusercontent.com/mevansam/pcf-pipelines/master/upgrade-ert/pipeline.yml

Patch Op: 
```
- op: remove
  path: /jobs/name=upgrade-tile/plan/task=apply-changes
```

This patch op removes `/jobs/name=upgrade-tile/plan/task=upload-stemcell` instead

**Comment by mevansam** [comment]
It appears that the search pointers are resolved before patches are applied. However, this causes problems as these pointers become invalid if a patch is applied before the op referenced by the resolved search pointer.

**Comment by krishicks** [comment]
I think it's reasonable to take the patches in any order; I'll look into making a reproducible test case.
