### ISSUE TITLE
Patch failure with two consecutive `remove` actions for an array object

### ISSUE THREAD

**Issue by lsilvapvt** [krishicks/yaml-patch#5]
When I try to remove two array entries (e.g. two tasks within a jobs object), yaml-patch fails to process the second one.
For example, for the operations file below:
```
---
- op: remove
  path: /jobs/name=upgrade-tile/task=wait-opsman-clear

- op: remove
  path: /jobs/name=upgrade-tile/task=apply-changes
```

When I try to run it against a yml file such as https://github.com/pivotal-cf/pcf-pipelines/blob/master/upgrade-tile/pipeline.yml, the following error occurs:
`error applying patch: Unable to remove invalid index: 5`

When I run each one of those operations in separate ops files individually (even sequentially), they work just fine.

**Comment by krishicks** [comment]
This should be fixed in https://github.com/krishicks/yaml-patch/commit/82ea669c1fe15d53aef9ed7803738c1a31719054.
